# 程序的基本信息
name: "bluebell"
mode: "dev"
version: "v0.1.2"
port: 8081
start_time: "2020-09-01"
machine_id: 1

auth:
  jwt_expire: 168 #24 * 7 过期时间为一周

# 日志配置
log:
  level: "debug"
  filename: "bluebell.log"
  max_size: 200 # 日志最大容量 (单位MB)
  max_age: 30 # 备份存储最大时间
  max_backup: 7 # 最大备份数量

# MySQL
mysql:
  host: "127.0.0.1"
  #host: mysql8019
  port: 3306
  user: "root"
  password: "644315"
  dbname: "bluebell"
  max_open_conns: 200 # 最大连接数
  max_idel_conns: 50 # 最大空闲连接数

# Reids
redis:
  host: "127.0.0.1"
  #host: redis507
  port: 6379
  password: "644315"
  db: 1
  pool_size: 100

